name: Build Project111

on:
  workflow_dispatch:
  push:
    branches: [ dev ]
  pull_request:
    branches: [ dev ]
jobs:
  build-and-test:
    runs-on: windows-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
        with:
          ref: dev
      - name: Setup .NET Framework
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 5.0.x

      - name: Restore NuGet Packages
        run: |
          cd ParserGUI
          nuget restore
      - name: Get Date
        id: date
        shell: pwsh
        run: |
          $date = Get-Date -Format "yyyyMMddHHmmss"
          echo "::set-output name=date::$date"
          
      - name: Build Solution
        run: |
          (Get-Item .).FullName
          Get-ChildItem
          cd ParserGUI
          (Get-Item .).FullName
          Get-ChildItem
          $env:Path += ";C:\Program Files\Microsoft Visual Studio\2022\Enterprise\MSBuild\Current\bin"
          msbuild /p:Configuration=Release ParserGUI.sln
          Get-ChildItem -Verbose
          Get-ChildItem -Verbose

      - name: Create Release
        id: create_release
        uses: zendesk/action-create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
        with:
          tag_name: ${{ github.run_number }} -${{ steps.date.outputs.date }} - ${{ github.sha }}
          release_name: Release ${{ github.ref }}
          draft: false
          prerelease: false
          auto_increment_type: path

      - name: Upload Asset
        id: upload-release-asset
        uses: actions/upload-release-asset@v1.0.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ParserGUI\ParserGUI\bin\Release\ParserGUI.exe
          asset_name: ParserGUI.exe
          asset_content_type: application/x-msdownload
