name: Build Project111

on:
  workflow_dispatch:
  push:
    branches: [ dev ]
  pull_request:
    branches: [ dev ]

# jobs:
#   build:

#     runs-on: windows-latest

#     steps:
#     - name: Checkout Repository
#       run: |
#         git clone --branch dev https://github.com/moevm/MSE-2023-msm-doc_parser-18.git
#         cd MSE-2023-msm-doc_parser-18/ParserGUI/
#         (Get-Item .).FullName
#         Get-ChildItem
        

#     - name: Setup .NET
#       uses: actions/setup-dotnet@v3
#       with:
#         dotnet-version: 6.0.x
jobs:
  build-and-test:
    runs-on: windows-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
        with:
          ref: dev
      - name: Setup .NET Framework
        uses: actions/setup-dotnet@v1
#         with:
#           dotnet-version: '4.8.x'

      - name: Restore NuGet Packages
        run: |
          cd ParserGUI
          nuget restore

      - name: Build Solution
        run: |
          cd ParserGUI
          msbuild /p:Configuration=Release ParserGUI.sln

      - name: Run Tests
        run: |
          cd ParserGUI
          $testResults = 'TestResults.trx'
          dotnet test ParserGUI.sln /p:CollectCoverage=true /p:CoverletOutputFormat=cobertura /p:CoverletOutput='./' /p:MergeWith='./coverage.xml' /p:Exclude=\"[xunit.*]*\" /p:Logger:trx /p:ResultsDirectory:./ /p:ResultsFile:$testResults /p:Configuration=Release
          
      - name: Publish Test Results
        uses: EnricoMi/publish-unit-test-result-action@v1
        with:
          testResultsFiles: 'ParserGUI/TestResults*.trx'
          type: VSTest
          name: 'MySolution Tests'
